language: python

python:
  - "3.5"

env:
  - DJANGO_SETTINGS_MODULE=ScheduleApp.settings
  CODACY_PROJECT_TOKEN:
    - secure: "1BBi3aTxFVzUoU8ntikWMZ6VM8QToeZL3w7EFbjWhiYVl9eNasJVBoobvc+iizPWaPBKQ5z9AGM0rj/lFmJtPHgDi/CQOHdIJb0cTuk327mlHevWBfFZoV0C8oREDm4Fs+hIqp+VX9Dnh6NgmlRPQuuiLhL0Uf7HxydRlb4llGzIoGsETPcBW0N7ypjAC0liL06NeBK75vg4J2UYNIbIIXwXphKKScHvSADQdzbALa66EQByH31t9IP6EiEZRAwiU3s61hnZVI52UHCAcYL7LpJC4lIrhWHXGd8NrtZLA+qSSsV9ZwXfaME8lcsYHknCjYTsne4EraJpL6Mmd/zeCa2AeEjxYw6n/+8BwHelUU+WIDB1+ZbuP/vttf+UCR65XR07ibxEVcLEir9NlTRWrMEX4FQycZX6T4lLPsuhlnYqhqIcuqttCyiFEPfcvwWwAKNM9yrSmHE6nPfgzawOGte3V2g+w7ZkBQTHJiqTaUUvkSjC+ZvWGRvNofQ217XdSWI3GFZPY8ff5+fwdfv0eYHQAM8qMd/WNkFwDjPvHJI/c+62Pz7Pov/VE4g0/TA9koCkY/YCi7iFH1eTYBO3JFSRJXG03FI7MlzctWZ8ughbSJ4v74cdhLUX7i916JKQdTqGHIRP3AL7WUn9gWNUcd+82gU5T9i0oEVqemRAScI="

install: "pip install -r requirements.txt"

script: sh ci_script.sh

notifications:
  slack: spbgti:DISw2DtYSQ3gQ8jB9NvTbSYG

deploy:
  provider: heroku
  api_key:
    secure: "EP0aof7lpo1hVzHpwGf+iVxoMX5BZSj3Z5AL1urBoGZ00BDxh+8RnG7/udeF71jPaFgevf10TgEHmlbwTBWqJ1GT1vN91k3adhV16zr+OgXhu9Q2sVRotVJSBLA49B3vTRpSxW1xMe56/Q5nTnmwkasb341r2wNzvacS5LeEv1QEo4tDXiSNq01ESN5XbG3h8s08hROfmttYtUFMeVIMqau85RaQKaqHyGdyN8HmPUbBVl6ebtIJ6TYjfnJwD7wnSPFBovpEzzU22C62qNFQrGXdSX0EpaLoqPqpPX+Qz2cygHSOEx2WfyWOY5PQlLWmyVhwjjg7gBFUaSWvFj0oXIye43R5GUvBF9JYSbqrxawk1vqGZhMNDonYb23DEqKLyIv0K4+eb2J14XCeOT7E9zsfpdxqO+zM1vOd79ZoXbRu2O7U3eGsUSejgM+jgAchiuz80scOM1ZV2nSXK3jiTe3ZPpM2Zr0A3Tyx4i3P01uxAebazY5hXkbBuVWPjOTlwe+FC7vKxV41YDQkkXw2pNVc0GE/0fCyoAcnkq0oEBAz+2/qL8FgFP9YpV3ifMi59+Fv9ek7GZ3gBuUAqPVWxGTKAg/jf27feQb1xR0aVG1vvcNkmlBdBZSqtHPEnMVEU04/2DLDkE6yEg4SKm+W0zyQbEgrdpPr4X5MlujaY9w="
  app:
    dev:
      spbgti-tools-schedule-staging
    master:
      spbgti-tools-schedule
  run:
    dev:
      - "sh heroku.sh --app spbgti-tools-schedule-staging"
    master:
      - "sh heroku.sh --app spbgti-tools-schedule"
  after_deploy:
    - echo "Running integration tests"
